### ISSUE TITLE
Data Load leads to white screen

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-api#37]
**Issue:** 
conditional rendering using Redux state works only for one of the conditions and not for the other.

**Detailed description:**
From our  Postgres database we pull a value named totalTours through an axios call (see loadTotalTours()), this value we save in a state inside redux store (same name), this works fine but when we do access it (inside Start component) and attempt to conditionally render the Header -depending on the value of totalTours- we get the expected behaviour for a value of >0 but not when the value == 0, for that we get an error (“Rendered fewer hooks than expected. This may be caused by an accidental early return statement.”).

**Related Files**: (frontend "zuugle_suchseite" repo)
Start/Start.js, Start/Header.js,  reducers/tours.js, actions/tourActions.js, actions/types.js, actions/crudActions.js

**Comment by martinheppner** [comment]
The situation can be provoced by setting total_tours=0 in PostgreSQL by executing:
`UPDATE kpi
SET value=0
WHERE name='total_tours';`

![Image](https://github.com/bahnzumberg/zuugle-api/assets/105971399/91616476-27d9-4b43-8eb8-788bc5179295)

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-api/assets/105971399/7e1b57a2-861d-49fe-8ad4-ee110d283e29)

**Comment by Falsal** [comment]
@martinheppner , the issue was that the error was coming in during rendering without data inside (as you are in useEffect), the solution was in the error and data unavailability cases inside the Redux store , now it  is done, we have the control now as to what to do in case of data is unavailable or in case of error in the call itself. 
Currently the behaviour is , that if we have a zero total_tours we get a header with the message "Zuugle befindet sich gerade im Wartungsmodus." , we need to clarify if this is what we need to do.

**Comment by Falsal** [comment]
/

**Comment by Falsal** [comment]
Hope you are feeling better Martin,

here is the link :
https://github.com/bahnzumberg/zuugle-suchseite/issues/215
Br
